blank_issues_enabled: false
contact_links:
  - name: Feature or Enhancement Request ✨
    url: https://github.com/Such-Software/hash-wallet/discussions
    about: Suggest an idea for Hash Bags
  - name: Need help?
    url: https://hash.boats
    about: Guides, support, and contact info
